### ISSUE TITLE
Create example files for Getting started guides 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/moov-io#22]
We should offer good example files (ach, wire, ICL, etc) for people to download. They can be hosted under `moov.io/demos/ppd-debit.ach`, which allows our guides to reference a quick `curl` to download them.

This would be combined with larger guides to GET and POST files against local/dev instances of ach, wire, ICL, etc.

**Comment by bkmoovio** [comment]
Thanks Adam!  I added you as an assigned as well.
