### ISSUE TITLE
site: fix support email 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/moov-io#36]
Today it was reported that `support@moov.io` and the contact form didn't work. I changed the email address to Wade's and verified the contact form worked. We need to enable that email. 

Thread: https://groups.google.com/forum/#!topic/moov-users/i7syW-BWPOs

Change: https://github.com/moov-io/moov-io/commit/363737a6ff9cd4d612277f3c876ac90f3301e28e

**Comment by wadearnold** [comment]
Mailing list added for support@moov.io - works like the security distribution list.
