### ISSUE TITLE
Change # coffee to # Twitter followers

### ISSUE THREAD

**Issue by wadearnold** [moov-io/moov-io#38]
Remove # coffee joke on home screen and replace it with # of twitter followers. 
Update Logo to Twitter logo from gift box 

<img width="241" alt="Screen Shot 2020-02-05 at 1 37 06 PM" src="https://user-images.githubusercontent.com/32989/73880936-a7d10900-481c-11ea-9a5e-5b01cd3a3e55.png">

**Comment by adamdecaf** [comment]
<img width="1181" alt="Screen Shot 2020-02-05 at 1 50 11 PM" src="https://user-images.githubusercontent.com/120951/73886478-9557cf00-481e-11ea-871f-374fa1060822.png">
